"""init_nat_batch_and_task_tables

Revision ID: 27baeba919ff
Revises:
Create Date: 2026-05-25 17:02:54.798547

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '27baeba919ff'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'nat_batches',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'file_name',
            sa.String(length=512),
            nullable=False,
            comment='Path to the uploaded file in backend/uploads/nat/',
        ),
        sa.Column(
            'row_count',
            sa.Integer(),
            nullable=False,
            comment='Number of rows in CSV file (excluding header)',
        ),
        sa.Column(
            'sender_email',
            sa.String(length=254),
            nullable=False,
            comment='Email address of the sender who submitted the batch attachment',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_batches')),
        comment='NAT batch files containing multiple processing requests',
    )
    op.create_index(
        op.f('ix_nat_batches_file_name'), 'nat_batches', ['file_name'], unique=False
    )
    op.create_index(op.f('ix_nat_batches_id'), 'nat_batches', ['id'], unique=False)
    op.create_index(
        op.f('ix_nat_batches_sender_email'),
        'nat_batches',
        ['sender_email'],
        unique=False,
    )
    op.create_table(
        'nat_tasks',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=False,
            nullable=False,
            comment='NAT API request ID (returned after ACTION=send). Used for polling.',
        ),
        sa.Column(
            'batch_id',
            sa.Uuid(),
            nullable=False,
            comment='Foreign key to parent NatBatch',
        ),
        sa.Column(
            'row_index',
            sa.Integer(),
            nullable=False,
            comment='Zero-based row index in the parent batch CSV file (excluding header)',
        ),
        sa.Column(
            'status',
            sa.Integer(),
            server_default=sa.text('-1'),
            nullable=False,
            comment='Processing status code from NAT API',
        ),
        sa.Column(
            'progress',
            sa.Integer(),
            nullable=True,
            comment='Progress percentage as returned by NAT API',
        ),
        sa.Column(
            'nat_response_file',
            sa.String(length=512),
            nullable=True,
            comment='Path to the response file from NAT (when status=30)',
        ),
        sa.Column(
            'count_of_lines',
            sa.String(length=32),
            nullable=True,
            comment='Number of lines in response (as returned by NAT, e.g., "12 345")',
        ),
        sa.Column(
            'file_size',
            sa.String(length=32),
            nullable=True,
            comment='Size of response file (as returned by NAT, e.g., "4.21MB")',
        ),
        sa.Column(
            'error_message',
            sa.Text(),
            nullable=True,
            comment='Error description if task failed',
        ),
        sa.Column(
            'retry_count',
            sa.Integer(),
            nullable=False,
            comment='Number of retry attempts',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['batch_id'],
            ['nat_batches.id'],
            name='fk_nat_tasks_batch_id_nat_batches',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_tasks')),
        sa.UniqueConstraint(
            'batch_id', 'row_index', name='uq_nat_tasks_batch_id_row_index'
        ),
        comment='Individual NAT tasks for each request in a batch file',
    )
    op.create_index(
        op.f('ix_nat_tasks_batch_id'), 'nat_tasks', ['batch_id'], unique=False
    )
    op.create_index(op.f('ix_nat_tasks_status'), 'nat_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nat_tasks_status'), table_name='nat_tasks')
    op.drop_index(op.f('ix_nat_tasks_batch_id'), table_name='nat_tasks')
    op.drop_table('nat_tasks')
    op.drop_index(op.f('ix_nat_batches_sender_email'), table_name='nat_batches')
    op.drop_index(op.f('ix_nat_batches_id'), table_name='nat_batches')
    op.drop_index(op.f('ix_nat_batches_file_name'), table_name='nat_batches')
    op.drop_table('nat_batches')
    # ### end Alembic commands ###
