"""add_email_message_reply_status

Revision ID: 38b37f135ff1
Revises: f64c9eb887a5
Create Date: 2026-06-04 11:44:24.573213

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38b37f135ff1'
down_revision: str | Sequence[str] | None = 'f64c9eb887a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'email_messages',
        sa.Column(
            'reply_status',
            sa.String(length=16),
            nullable=True,
            comment='Outbound reply delivery status: sent, failed, or null if not applicable',
        ),
    )
    op.create_index(
        op.f('ix_email_messages_reply_status'),
        'email_messages',
        ['reply_status'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_reply_status'), table_name='email_messages')
    op.drop_column('email_messages', 'reply_status')
    # ### end Alembic commands ###
