"""update_nat_tasks_for_status_worker

Revision ID: beaa9e5f91e3
Revises: 38b37f135ff1
Create Date: 2026-06-11 12:39:56.842491

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'beaa9e5f91e3'
down_revision: str | Sequence[str] | None = '38b37f135ff1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'nat_task_result_files',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'task_id',
            sa.Uuid(),
            nullable=False,
            comment='Foreign key to parent NatTask',
        ),
        sa.Column(
            'nat_file_id',
            sa.Integer(),
            nullable=False,
            comment='File ID from NAT API files[] response',
        ),
        sa.Column(
            'file_url',
            sa.String(length=2048),
            nullable=False,
            comment='Download URL from NAT API',
        ),
        sa.Column(
            'file_size',
            sa.String(length=32),
            nullable=True,
            comment='File size as returned by NAT API',
        ),
        sa.Column(
            'file_type',
            sa.String(length=32),
            nullable=True,
            comment='File type as returned by NAT API',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['task_id'],
            ['nat_tasks.id'],
            name='fk_nat_task_result_files_task_id_nat_tasks',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_task_result_files')),
        comment='Result files returned by NAT API for a completed or in-progress task',
    )
    op.create_index(
        op.f('ix_nat_task_result_files_task_id'),
        'nat_task_result_files',
        ['task_id'],
        unique=False,
    )
    op.alter_column(
        'nat_tasks',
        'datetime_from',
        existing_type=sa.VARCHAR(length=32),
        type_=sa.DateTime(timezone=True),
        comment='Start datetime for NAT request',
        existing_comment='Start datetime for NAT request (dd.mm.yyyy hh:mm:ss)',
        existing_nullable=False,
        postgresql_using=(
            "to_timestamp(datetime_from, 'DD.MM.YYYY HH24:MI:SS') AT TIME ZONE 'UTC'"
        ),
    )
    op.alter_column(
        'nat_tasks',
        'datetime_to',
        existing_type=sa.VARCHAR(length=32),
        type_=sa.DateTime(timezone=True),
        comment='End datetime for NAT request',
        existing_comment='End datetime for NAT request (dd.mm.yyyy hh:mm:ss)',
        existing_nullable=False,
        postgresql_using=(
            "to_timestamp(datetime_to, 'DD.MM.YYYY HH24:MI:SS') AT TIME ZONE 'UTC'"
        ),
    )
    op.alter_column(
        'nat_tasks',
        'progress',
        existing_type=sa.INTEGER(),
        type_=sa.String(length=32),
        comment='Progress as returned by NAT API (e.g., "100.00")',
        existing_comment='Progress percentage as returned by NAT API',
        existing_nullable=True,
        postgresql_using='progress::text',
    )
    op.create_index(
        'ix_nat_tasks_dispatch_queue',
        'nat_tasks',
        ['created_at'],
        unique=False,
        postgresql_where=sa.text('status IS NULL AND error_message IS NULL'),
    )
    op.create_index(
        'ix_nat_tasks_poll_queue',
        'nat_tasks',
        ['created_at'],
        unique=False,
        postgresql_where=sa.text('status IN (10, 20, -1)'),
    )
    op.drop_column('nat_tasks', 'nat_response_file')
    op.drop_column('nat_tasks', 'file_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'nat_tasks',
        sa.Column(
            'file_size',
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=True,
            comment='Size of response file (as returned by NAT, e.g., "4.21MB")',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'nat_response_file',
            sa.VARCHAR(length=512),
            autoincrement=False,
            nullable=True,
            comment='Path to the response file from NAT (when status=30)',
        ),
    )
    op.drop_index(
        'ix_nat_tasks_poll_queue',
        table_name='nat_tasks',
        postgresql_where=sa.text('status IN (10, 20, -1)'),
    )
    op.drop_index(
        'ix_nat_tasks_dispatch_queue',
        table_name='nat_tasks',
        postgresql_where=sa.text('status IS NULL AND error_message IS NULL'),
    )
    op.alter_column(
        'nat_tasks',
        'progress',
        existing_type=sa.String(length=32),
        type_=sa.INTEGER(),
        comment='Progress percentage as returned by NAT API',
        existing_comment='Progress as returned by NAT API (e.g., "100.00")',
        existing_nullable=True,
        postgresql_using='progress::integer',
    )
    op.alter_column(
        'nat_tasks',
        'datetime_to',
        existing_type=sa.DateTime(timezone=True),
        type_=sa.VARCHAR(length=32),
        comment='End datetime for NAT request (dd.mm.yyyy hh:mm:ss)',
        existing_comment='End datetime for NAT request',
        existing_nullable=False,
        postgresql_using=(
            "to_char(datetime_to AT TIME ZONE 'UTC', 'DD.MM.YYYY HH24:MI:SS')"
        ),
    )
    op.alter_column(
        'nat_tasks',
        'datetime_from',
        existing_type=sa.DateTime(timezone=True),
        type_=sa.VARCHAR(length=32),
        comment='Start datetime for NAT request (dd.mm.yyyy hh:mm:ss)',
        existing_comment='Start datetime for NAT request',
        existing_nullable=False,
        postgresql_using=(
            "to_char(datetime_from AT TIME ZONE 'UTC', 'DD.MM.YYYY HH24:MI:SS')"
        ),
    )
    op.drop_index(
        op.f('ix_nat_task_result_files_task_id'), table_name='nat_task_result_files'
    )
    op.drop_table('nat_task_result_files')
    # ### end Alembic commands ###
