"""refactor_nat_tasks_for_intake_persistence

Revision ID: dee2cd771fd5
Revises: 5848da667f9e
Create Date: 2026-05-27 12:36:58.849068

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dee2cd771fd5'
down_revision: str | Sequence[str] | None = '5848da667f9e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'nat_batches',
        'row_count',
        existing_type=sa.INTEGER(),
        comment='Number of rows in file (excluding header)',
        existing_comment='Number of rows in CSV file (excluding header)',
        existing_nullable=False,
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'nat_request_id',
            sa.Integer(),
            nullable=True,
            comment='NAT API request ID (returned after ACTION=send). Used for polling.',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'datetime_from',
            sa.String(length=32),
            nullable=False,
            comment='Start datetime for NAT request (dd.mm.yyyy hh:mm:ss)',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'datetime_to',
            sa.String(length=32),
            nullable=False,
            comment='End datetime for NAT request (dd.mm.yyyy hh:mm:ss)',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'src_xlated',
            sa.String(length=45),
            nullable=False,
            comment='External source IPv4 for NAT request',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'src_port_xlated',
            sa.Integer(),
            nullable=True,
            comment='External source port for NAT request',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'src',
            sa.String(length=45),
            nullable=False,
            comment='Internal source IPv4 for NAT request',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'src_port',
            sa.Integer(),
            nullable=True,
            comment='Internal source port for NAT request',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'dst',
            sa.String(length=45),
            nullable=False,
            comment='Destination IPv4 for NAT request',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'dst_port',
            sa.Integer(),
            nullable=True,
            comment='Destination port for NAT request',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'region',
            sa.String(length=8),
            nullable=False,
            comment='Region code for NAT request (1-8 or placeholder)',
        ),
    )
    op.alter_column(
        'nat_tasks',
        'id',
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        comment='Primary key (UUID v4, generated automatically)',
        existing_comment='NAT API request ID (returned after ACTION=send). Used for polling.',
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f('uq_nat_tasks_batch_id_row_index'), 'nat_tasks', type_='unique'
    )
    op.create_index(op.f('ix_nat_tasks_id'), 'nat_tasks', ['id'], unique=False)
    op.create_index(
        op.f('ix_nat_tasks_nat_request_id'),
        'nat_tasks',
        ['nat_request_id'],
        unique=False,
    )
    op.drop_column('nat_tasks', 'row_index')
    op.drop_column('nat_tasks', 'retry_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'nat_tasks',
        sa.Column(
            'retry_count',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment='Number of retry attempts',
        ),
    )
    op.add_column(
        'nat_tasks',
        sa.Column(
            'row_index',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment='Zero-based row index in the parent batch CSV file (excluding header)',
        ),
    )
    op.drop_index(op.f('ix_nat_tasks_nat_request_id'), table_name='nat_tasks')
    op.drop_index(op.f('ix_nat_tasks_id'), table_name='nat_tasks')
    op.create_unique_constraint(
        op.f('uq_nat_tasks_batch_id_row_index'),
        'nat_tasks',
        ['batch_id', 'row_index'],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        'nat_tasks',
        'id',
        existing_type=sa.Uuid(),
        type_=sa.INTEGER(),
        comment='NAT API request ID (returned after ACTION=send). Used for polling.',
        existing_comment='Primary key (UUID v4, generated automatically)',
        existing_nullable=False,
    )
    op.drop_column('nat_tasks', 'region')
    op.drop_column('nat_tasks', 'dst_port')
    op.drop_column('nat_tasks', 'dst')
    op.drop_column('nat_tasks', 'src_port')
    op.drop_column('nat_tasks', 'src')
    op.drop_column('nat_tasks', 'src_port_xlated')
    op.drop_column('nat_tasks', 'src_xlated')
    op.drop_column('nat_tasks', 'datetime_to')
    op.drop_column('nat_tasks', 'datetime_from')
    op.drop_column('nat_tasks', 'nat_request_id')
    op.alter_column(
        'nat_batches',
        'row_count',
        existing_type=sa.INTEGER(),
        comment='Number of rows in CSV file (excluding header)',
        existing_comment='Number of rows in file (excluding header)',
        existing_nullable=False,
    )
    # ### end Alembic commands ###
