"""add_email_poller_schema

Revision ID: f64c9eb887a5
Revises: 4031e5e4f85c
Create Date: 2026-06-02 21:19:32.324558

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f64c9eb887a5'
down_revision: str | Sequence[str] | None = '4031e5e4f85c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'email_senders',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'email',
            sa.String(length=254),
            nullable=False,
            comment='Whitelisted sender address (lowercase)',
        ),
        sa.Column(
            'name',
            sa.String(length=100),
            nullable=True,
            comment='Display name for the sender',
        ),
        sa.Column(
            'contact',
            sa.String(length=200),
            nullable=True,
            comment='Optional contact information',
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            comment='Whether the sender is included in IMAP monitoring',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_email_senders')),
        sa.UniqueConstraint('email', name=op.f('uq_email_senders_email')),
        comment='Whitelisted email senders allowed to submit files via IMAP',
    )
    op.create_table(
        'email_messages',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'message_id',
            sa.String(length=1000),
            nullable=False,
            comment='RFC Message-ID or surrogate id for deduplication',
        ),
        sa.Column(
            'sender_email',
            sa.String(length=254),
            nullable=False,
            comment='Normalized sender address from the email From header',
        ),
        sa.Column(
            'subject',
            sa.String(length=1000),
            nullable=True,
            comment='Decoded email subject',
        ),
        sa.Column(
            'body',
            sa.Text(),
            nullable=True,
            comment='Plain-text body extracted from the email',
        ),
        sa.Column(
            'received_at',
            sa.DateTime(timezone=True),
            nullable=False,
            comment='Received timestamp from Date header or processing time',
        ),
        sa.Column(
            'processing_status',
            sa.String(length=32),
            nullable=False,
            comment='Processing outcome: accepted, rejected, or skipped',
        ),
        sa.Column(
            'nat_intake_id',
            sa.Uuid(),
            nullable=True,
            comment='Linked NAT intake after B2B processing (null when skipped)',
        ),
        sa.Column(
            'error_code',
            sa.String(length=64),
            nullable=True,
            comment='Error code from IntakeResponse when status is rejected',
        ),
        sa.Column(
            'error_message',
            sa.Text(),
            nullable=True,
            comment='Error message from IntakeResponse when status is rejected',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['nat_intake_id'],
            ['nat_intakes.id'],
            name='fk_email_messages_nat_intake_id_nat_intakes',
            ondelete='SET NULL',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_email_messages')),
        sa.UniqueConstraint('message_id', name=op.f('uq_email_messages_message_id')),
        comment='Audit log of emails processed by the IMAP poller',
    )
    op.create_index(
        op.f('ix_email_messages_id'), 'email_messages', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_email_messages_nat_intake_id'),
        'email_messages',
        ['nat_intake_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_email_messages_processing_status'),
        'email_messages',
        ['processing_status'],
        unique=False,
    )
    op.create_index(
        op.f('ix_email_messages_sender_email'),
        'email_messages',
        ['sender_email'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_sender_email'), table_name='email_messages')
    op.drop_index(
        op.f('ix_email_messages_processing_status'), table_name='email_messages'
    )
    op.drop_index(op.f('ix_email_messages_nat_intake_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_id'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_table('email_senders')
    # ### end Alembic commands ###
