"""init schema

Revision ID: cb675b40cf81
Revises:
Create Date: 2026-06-18 09:35:41.936089

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cb675b40cf81'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'email_senders',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'email',
            sa.String(length=254),
            nullable=False,
            comment='Whitelisted sender address (lowercase)',
        ),
        sa.Column(
            'name',
            sa.String(length=100),
            nullable=True,
            comment='Display name for the sender',
        ),
        sa.Column(
            'contact',
            sa.String(length=200),
            nullable=True,
            comment='Optional contact information',
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            comment='Whether the sender is included in IMAP monitoring',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_email_senders')),
        sa.UniqueConstraint('email', name=op.f('uq_email_senders_email')),
        comment='Whitelisted email senders allowed to submit files via IMAP',
    )
    op.create_table(
        'nat_dedup_keys',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'key_hash',
            sa.String(length=64),
            nullable=False,
            comment='SHA-256 hash of the deduplication key fields',
        ),
        sa.Column(
            'date_from',
            sa.DateTime(timezone=True),
            nullable=False,
            comment='Start datetime from the deduplication key',
        ),
        sa.Column(
            'date_to',
            sa.DateTime(timezone=True),
            nullable=False,
            comment='End datetime from the deduplication key',
        ),
        sa.Column(
            'internal_ip',
            sa.String(length=45),
            nullable=True,
            comment='Internal IP from the deduplication key',
        ),
        sa.Column(
            'external_ip',
            sa.String(length=45),
            nullable=True,
            comment='External IP from the deduplication key',
        ),
        sa.Column(
            'resource_ip',
            sa.String(length=45),
            nullable=True,
            comment='Resource IP from the deduplication key',
        ),
        sa.Column(
            'region',
            sa.String(length=8),
            nullable=True,
            comment='Region code from the deduplication key',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_dedup_keys')),
        sa.UniqueConstraint('key_hash', name=op.f('uq_nat_dedup_keys_key_hash')),
        comment='Registered deduplication keys for idempotency window tracking',
    )
    op.create_table(
        'nat_intakes',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'sender_email',
            sa.String(length=254),
            nullable=False,
            comment='Email address of the user who submitted the file',
        ),
        sa.Column(
            'file_name',
            sa.String(length=512),
            nullable=False,
            comment='Original uploaded file name',
        ),
        sa.Column(
            'status',
            sa.String(length=32),
            nullable=False,
            comment='Intake processing status (accepted, partially_accepted, rejected)',
        ),
        sa.Column(
            'error_code',
            sa.String(length=64),
            nullable=True,
            comment='File-level validation error code when the intake is rejected',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_intakes')),
        comment='NAT file intake attempts including rejected and accepted uploads',
    )
    op.create_index(op.f('ix_nat_intakes_id'), 'nat_intakes', ['id'], unique=False)
    op.create_index(
        op.f('ix_nat_intakes_sender_email'),
        'nat_intakes',
        ['sender_email'],
        unique=False,
    )
    op.create_index(
        op.f('ix_nat_intakes_status'), 'nat_intakes', ['status'], unique=False
    )
    op.create_table(
        'email_messages',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'message_id',
            sa.String(length=1000),
            nullable=False,
            comment='RFC Message-ID or surrogate id for deduplication',
        ),
        sa.Column(
            'sender_email',
            sa.String(length=254),
            nullable=False,
            comment='Normalized sender address from the email From header',
        ),
        sa.Column(
            'subject',
            sa.String(length=1000),
            nullable=True,
            comment='Decoded email subject',
        ),
        sa.Column(
            'body',
            sa.Text(),
            nullable=True,
            comment='Plain-text body extracted from the email',
        ),
        sa.Column(
            'received_at',
            sa.DateTime(timezone=True),
            nullable=False,
            comment='Received timestamp from Date header or processing time',
        ),
        sa.Column(
            'processing_status',
            sa.String(length=32),
            nullable=False,
            comment='Processing outcome: accepted, rejected, or skipped',
        ),
        sa.Column(
            'nat_intake_id',
            sa.Uuid(),
            nullable=True,
            comment='Linked NAT intake after B2B processing (null when skipped)',
        ),
        sa.Column(
            'error_code',
            sa.String(length=64),
            nullable=True,
            comment='Error code from IntakeResponse when status is rejected',
        ),
        sa.Column(
            'error_message',
            sa.Text(),
            nullable=True,
            comment='Error message from IntakeResponse when status is rejected',
        ),
        sa.Column(
            'reply_status',
            sa.String(length=16),
            nullable=True,
            comment='Outbound reply delivery status: sent, failed, or null if not applicable',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['nat_intake_id'],
            ['nat_intakes.id'],
            name='fk_email_messages_nat_intake_id_nat_intakes',
            ondelete='SET NULL',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_email_messages')),
        sa.UniqueConstraint('message_id', name=op.f('uq_email_messages_message_id')),
        comment='Audit log of emails processed by the IMAP poller',
    )
    op.create_index(
        op.f('ix_email_messages_id'), 'email_messages', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_email_messages_nat_intake_id'),
        'email_messages',
        ['nat_intake_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_email_messages_processing_status'),
        'email_messages',
        ['processing_status'],
        unique=False,
    )
    op.create_index(
        op.f('ix_email_messages_reply_status'),
        'email_messages',
        ['reply_status'],
        unique=False,
    )
    op.create_index(
        op.f('ix_email_messages_sender_email'),
        'email_messages',
        ['sender_email'],
        unique=False,
    )
    op.create_table(
        'nat_batches',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'intake_id',
            sa.Uuid(),
            nullable=False,
            comment='Foreign key to parent NatIntake',
        ),
        sa.Column(
            'file_name',
            sa.String(length=512),
            nullable=False,
            comment='Path to the uploaded file in backend/uploads/nat/',
        ),
        sa.Column(
            'row_count',
            sa.Integer(),
            nullable=False,
            comment='Number of rows in file (excluding header)',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['intake_id'],
            ['nat_intakes.id'],
            name='fk_nat_batches_intake_id_nat_intakes',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_batches')),
        comment='NAT batch files containing multiple processing requests',
    )
    op.create_index(
        op.f('ix_nat_batches_file_name'), 'nat_batches', ['file_name'], unique=False
    )
    op.create_index(op.f('ix_nat_batches_id'), 'nat_batches', ['id'], unique=False)
    op.create_index(
        op.f('ix_nat_batches_intake_id'), 'nat_batches', ['intake_id'], unique=True
    )
    op.create_table(
        'nat_intake_row_errors',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'intake_id',
            sa.Uuid(),
            nullable=False,
            comment='Foreign key to parent NatIntake',
        ),
        sa.Column(
            'row_number',
            sa.Integer(),
            nullable=False,
            comment='1-based row number in the uploaded file',
        ),
        sa.Column(
            'error_code',
            sa.String(length=64),
            nullable=False,
            comment='Row-level error code from validation, deduplication, or transformation',
        ),
        sa.Column(
            'column',
            sa.String(length=64),
            nullable=True,
            comment='Input column name related to the error, when applicable',
        ),
        sa.ForeignKeyConstraint(
            ['intake_id'],
            ['nat_intakes.id'],
            name='fk_nat_intake_row_errors_intake_id_nat_intakes',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_intake_row_errors')),
        comment='Row-level errors collected during NAT intake processing',
    )
    op.create_index(
        op.f('ix_nat_intake_row_errors_intake_id'),
        'nat_intake_row_errors',
        ['intake_id'],
        unique=False,
    )
    op.create_table(
        'nat_tasks',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'batch_id',
            sa.Uuid(),
            nullable=False,
            comment='Foreign key to parent NatBatch',
        ),
        sa.Column(
            'nat_request_id',
            sa.Integer(),
            nullable=True,
            comment='NAT API request ID (returned after ACTION=send). Used for polling.',
        ),
        sa.Column(
            'datetime_from',
            sa.DateTime(timezone=True),
            nullable=False,
            comment='Start datetime for NAT request',
        ),
        sa.Column(
            'datetime_to',
            sa.DateTime(timezone=True),
            nullable=False,
            comment='End datetime for NAT request',
        ),
        sa.Column(
            'src_xlated',
            sa.String(length=45),
            nullable=False,
            comment='External source IPv4 for NAT request',
        ),
        sa.Column(
            'src_port_xlated',
            sa.Integer(),
            nullable=True,
            comment='External source port for NAT request',
        ),
        sa.Column(
            'src',
            sa.String(length=45),
            nullable=False,
            comment='Internal source IPv4 for NAT request',
        ),
        sa.Column(
            'src_port',
            sa.Integer(),
            nullable=True,
            comment='Internal source port for NAT request',
        ),
        sa.Column(
            'dst',
            sa.String(length=45),
            nullable=False,
            comment='Destination IPv4 for NAT request',
        ),
        sa.Column(
            'dst_port',
            sa.Integer(),
            nullable=True,
            comment='Destination port for NAT request',
        ),
        sa.Column(
            'region',
            sa.String(length=8),
            nullable=False,
            comment='Region code for NAT request (1-8 or placeholder)',
        ),
        sa.Column(
            'status',
            sa.Integer(),
            nullable=True,
            comment='Processing status code from NAT API; NULL until assigned',
        ),
        sa.Column(
            'progress',
            sa.String(length=32),
            nullable=True,
            comment='Progress as returned by NAT API (e.g., "100.00")',
        ),
        sa.Column(
            'count_of_lines',
            sa.String(length=32),
            nullable=True,
            comment='Number of lines in response (as returned by NAT, e.g., "12 345")',
        ),
        sa.Column(
            'nat_file_id',
            sa.Integer(),
            nullable=True,
            comment='File ID from NAT API files[] response',
        ),
        sa.Column(
            'file_url',
            sa.String(length=2048),
            nullable=True,
            comment='Download URL from NAT API',
        ),
        sa.Column(
            'file_size',
            sa.String(length=32),
            nullable=True,
            comment='File size as returned by NAT API',
        ),
        sa.Column(
            'file_type',
            sa.String(length=32),
            nullable=True,
            comment='File type as returned by NAT API',
        ),
        sa.Column(
            'error_message',
            sa.Text(),
            nullable=True,
            comment='Error description if task failed',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['batch_id'],
            ['nat_batches.id'],
            name='fk_nat_tasks_batch_id_nat_batches',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_tasks')),
        comment='Individual NAT tasks for each request in a batch file',
    )
    op.create_index(
        op.f('ix_nat_tasks_batch_id'), 'nat_tasks', ['batch_id'], unique=False
    )
    op.create_index(
        'ix_nat_tasks_dispatch_queue',
        'nat_tasks',
        ['created_at'],
        unique=False,
        postgresql_where=sa.text('status IS NULL AND error_message IS NULL'),
    )
    op.create_index(op.f('ix_nat_tasks_id'), 'nat_tasks', ['id'], unique=False)
    op.create_index(
        op.f('ix_nat_tasks_nat_request_id'),
        'nat_tasks',
        ['nat_request_id'],
        unique=False,
    )
    op.create_index(
        'ix_nat_tasks_poll_queue',
        'nat_tasks',
        ['created_at'],
        unique=False,
        postgresql_where=sa.text('status IN (10, 20, -1)'),
    )
    op.create_index(op.f('ix_nat_tasks_status'), 'nat_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nat_tasks_status'), table_name='nat_tasks')
    op.drop_index(
        'ix_nat_tasks_poll_queue',
        table_name='nat_tasks',
        postgresql_where=sa.text('status IN (10, 20, -1)'),
    )
    op.drop_index(op.f('ix_nat_tasks_nat_request_id'), table_name='nat_tasks')
    op.drop_index(op.f('ix_nat_tasks_id'), table_name='nat_tasks')
    op.drop_index(
        'ix_nat_tasks_dispatch_queue',
        table_name='nat_tasks',
        postgresql_where=sa.text('status IS NULL AND error_message IS NULL'),
    )
    op.drop_index(op.f('ix_nat_tasks_batch_id'), table_name='nat_tasks')
    op.drop_table('nat_tasks')
    op.drop_index(
        op.f('ix_nat_intake_row_errors_intake_id'), table_name='nat_intake_row_errors'
    )
    op.drop_table('nat_intake_row_errors')
    op.drop_index(op.f('ix_nat_batches_intake_id'), table_name='nat_batches')
    op.drop_index(op.f('ix_nat_batches_id'), table_name='nat_batches')
    op.drop_index(op.f('ix_nat_batches_file_name'), table_name='nat_batches')
    op.drop_table('nat_batches')
    op.drop_index(op.f('ix_email_messages_sender_email'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_reply_status'), table_name='email_messages')
    op.drop_index(
        op.f('ix_email_messages_processing_status'), table_name='email_messages'
    )
    op.drop_index(op.f('ix_email_messages_nat_intake_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_id'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_nat_intakes_status'), table_name='nat_intakes')
    op.drop_index(op.f('ix_nat_intakes_sender_email'), table_name='nat_intakes')
    op.drop_index(op.f('ix_nat_intakes_id'), table_name='nat_intakes')
    op.drop_table('nat_intakes')
    op.drop_table('nat_dedup_keys')
    op.drop_table('email_senders')
    # ### end Alembic commands ###
