"""add_nat_dedup_keys_table

Revision ID: 5848da667f9e
Revises: 27baeba919ff
Create Date: 2026-05-25 20:50:28.365407

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5848da667f9e'
down_revision: str | Sequence[str] | None = '27baeba919ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'nat_dedup_keys',
        sa.Column(
            'id',
            sa.Uuid(),
            nullable=False,
            comment='Primary key (UUID v4, generated automatically)',
        ),
        sa.Column(
            'key_hash',
            sa.String(length=64),
            nullable=False,
            comment='SHA-256 hash of the deduplication key fields',
        ),
        sa.Column(
            'date_from',
            sa.DateTime(timezone=True),
            nullable=False,
            comment='Start datetime from the deduplication key',
        ),
        sa.Column(
            'date_to',
            sa.DateTime(timezone=True),
            nullable=False,
            comment='End datetime from the deduplication key',
        ),
        sa.Column(
            'internal_ip',
            sa.String(length=45),
            nullable=True,
            comment='Internal IP from the deduplication key',
        ),
        sa.Column(
            'external_ip',
            sa.String(length=45),
            nullable=True,
            comment='External IP from the deduplication key',
        ),
        sa.Column(
            'resource_ip',
            sa.String(length=45),
            nullable=True,
            comment='Resource IP from the deduplication key',
        ),
        sa.Column(
            'region',
            sa.String(length=8),
            nullable=True,
            comment='Region code from the deduplication key',
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_nat_dedup_keys')),
        comment='Registered deduplication keys for idempotency window tracking',
    )
    op.create_index(
        op.f('ix_nat_dedup_keys_key_hash'), 'nat_dedup_keys', ['key_hash'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nat_dedup_keys_key_hash'), table_name='nat_dedup_keys')
    op.drop_table('nat_dedup_keys')
    # ### end Alembic commands ###
