from enum import StrEnum

EMAIL_POLLER_SERVICE_ROLE = 'service:email-poller'
SENDER_MANAGER_ROLE = 'sender_manager'


class AuthErrorCode(StrEnum):
    MISSING_EMAIL = 'MISSING_EMAIL'
    UNAUTHORIZED_SERVICE = 'UNAUTHORIZED_SERVICE'
    INVALID_SENDER_EMAIL = 'INVALID_SENDER_EMAIL'
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS'
