from enum import StrEnum


class EmailProcessingStatus(StrEnum):
    ACCEPTED = 'accepted'
    REJECTED = 'rejected'
    SKIPPED = 'skipped'


class EmailSkipReason(StrEnum):
    SENDER_NOT_WHITELISTED = 'SENDER_NOT_WHITELISTED'
    NO_ALLOWED_ATTACHMENT = 'NO_ALLOWED_ATTACHMENT'
    PARSE_FAILED = 'PARSE_FAILED'
    NAT_B2B_FAILED = 'NAT_B2B_FAILED'


EMAIL_PARSE_FAILURE_SENDER = 'unknown@invalid.local'

EMAIL_REPLY_FILTER_NULL_SENTINEL = 'null'


class EmailReplyStatus(StrEnum):
    SENT = 'sent'
    FAILED = 'failed'


class EmailApiErrorCode(StrEnum):
    SENDER_NOT_FOUND = 'SENDER_NOT_FOUND'
    MESSAGE_NOT_FOUND = 'MESSAGE_NOT_FOUND'
    SENDER_ALREADY_EXISTS = 'SENDER_ALREADY_EXISTS'
    INVALID_FILTER_PROCESSING_STATUS = 'INVALID_FILTER_PROCESSING_STATUS'
    INVALID_FILTER_REPLY_STATUS = 'INVALID_FILTER_REPLY_STATUS'
